### ISSUE TITLE
Arreglar fallos tipográficos

### ISSUE THREAD

**Issue by deantares** [geneura-papers/2015-ENTCOM-GPBot#11]
[ ] There is a typo in the label of Figure 14: 'reinforces' should be 'reinforcements'
[ x] wrong name in [8](done if it's Baeck)
[ ] wrong characters in [18], ..
(no idea)
[ ] page 5 : "Planet Wars bots [?]"
(no idea)
[x] page 7 : you should include a caption to the code
(actually explained in the lines above)
[x]page 21 : the "Acknowledgements" is empty, should be removed
[x] references 13 and 26 are not articles, should be included as footnote
I don't know what they mean, if it's the Wikipedia article, it's better that way.

**Comment by JJ** [comment]
If someone has corrected this, which apparently has, he or she should have made a reference to this issue...

**Comment by JJ** [comment]
I don't know what gives. There's no Figure 14 in my version of the paper. What is [8] and [18]? I'll try with the rest (except it takes time for my changes to appear)

**Comment by amorag** [comment]
Closed in ff8e90d382c66e25414b10639b8be9c6442a0e0f
